POST http://localhost:3000/create-manager
Content-Type: application/json

{
    "first_name": "Abner",
    "last_name": "Penig",
    "employee_email": "Penig@gmail.com",
    "contact_number": "09457331226",
    "employee_status": "active"
}